### PR TITLE
Add CLP image and link to Zulip server

### PR DESCRIPTION
**Pull request by kirkrodrigues**

### CODE REVIEW

**Comment by vishalpalaniappan** [comment]
Would it be helpful to have the bug reporting and Zulip under a separate heading called "Community, Support and Feedback"?

**Review by vishalpalaniappan — APPROVED** [review]
Looks great!

**Review by vishalpalaniappan — APPROVED** [review]

**Review by vishalpalaniappan — APPROVED** [review]

**Review by vishalpalaniappan — APPROVED** [review]

**Review by davidlion — APPROVED** [review]

**Comment by vishalpalaniappan** [comment]
Commit Message:
Add CLP image and link to Zulip server (#94)

Let me know if you want me to modify it.

**Comment by kirkrodrigues** [comment]
lgtm

**Pull request merged**
